<?php 
 /**
   * @var \PromCMS\Core\PromConfig\Entity $entity
   */
echo "<?php\n"; 
?>
/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync. 
 */

namespace <?php echo $entity->namespace; ?>\Base;

enum <?php echo $enum['name'] ?>: string {
  <?php foreach ($enum['values'] as $enumKey => $enumValue): ?>
case <?php echo $enumKey ?> = "<?php echo $enumValue ?>";
  <?php endforeach ; ?>
}
