<?php
/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync. 
 * Updates should be made to ../UserRole.php as that is not overriden.
 */

namespace PromCMS\Core\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Models\Mapping as Mapping;
use PromCMS\Core\Models\Abstract\BaseModel;

#[ORM\Entity]
#[ORM\Table(name: 'prom__user_roles')]
#[Mapping\PromModel(ignoreSeeding: true)]
class UserRole extends BaseModel
{
  use \PromCMS\Core\Models\Trait\Timestamps;
      #[ORM\Column(
      type: 'string', 
      unique: true,
      name: 'label',
      nullable: false,
    )]
    #[Mapping\PromModelColumn(
      title: 'Label', 
      type: 'string',
      editable: 'true',
      hide: 'false',
      localized: 'false'
    )]
    private string $label;
    
      #[ORM\Column(
      type: 'array', 
      name: 'permissions',
      nullable: true,
    )]
    #[Mapping\PromModelColumn(
      title: 'Permissions', 
      type: 'json',
      editable: 'true',
      hide: 'false',
      localized: 'false'
    )]
    private ?array $permissions = [];
    
      #[ORM\Column(
      type: 'text', 
      name: 'description',
      nullable: true,
    )]
    #[Mapping\PromModelColumn(
      title: 'Description', 
      type: 'longText',
      editable: 'true',
      hide: 'false',
      localized: 'false'
    )]
    private ?string $description;
    
  
  public function __construct() {
          }
}
