<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 * Updates should be made to ../FileTranslation.php as that is not overriden.
 */

namespace PromCMS\Core\Database\Models\Base;

use Doctrine\ORM\Mapping as ORM;
use PromCMS\Core\Database\Models\Mapping as PROM;
use Doctrine\Common\Collections\ArrayCollection;
use PromCMS\Core\Database\Models\Abstract\Entity;

#[ORM\MappedSuperclass]
class FileTranslation extends Entity
{
  use \PromCMS\Core\Database\Models\Trait\NumericId;
  use \PromCMS\Core\Database\Models\Trait\Timestamps;
  
  #[ORM\Column(type: 'string', name: 'locale', nullable: false)]
  protected string $locale;
  
  #[ORM\ManyToOne(targetEntity: \PromCMS\Core\Database\Models\File::class, inversedBy: 'translations'), ORM\JoinColumn(name: 'object_id', nullable: false)]
  protected \PromCMS\Core\Database\Models\File $object;
  
  #[ORM\Column(name: 'description', nullable: true, unique: false, type: 'text'), PROM\PromModelColumn(title: 'Description', type: 'longText', editable: false, hide: false, localized: true)]
  protected ?string $description;
  
  function __construct(string $locale)
  {
    $this->locale = $locale;
  }
  
  #[ORM\PostLoad]
  function __prom__initCollections()
  {
  }
  
  function getDescription(): ?string
  {
    return $this->description;
  }
  
  function setDescription(?string $description): static
  {
    $this->description = $description;
    return $this;
  }
  
  function setObject(\PromCMS\Core\Database\Models\File $object): static
  {
    $this->object = $object;
    return $this;
  }
  
  function getLocale(): string
  {
    return $this->locale;
  }
}