<?php

/**
 * This file is generated by PromCMS, do not edit this file as changes made to this file will be overriden in the next model sync.
 */

namespace PromCMS\Core\Database\Models\Base;

enum UserState : string
{
  case ACTIVE = 'active';
  case INVITED = 'invited';
  case BLOCKED = 'blocked';
  case PASSWORD_RESET = 'password-reset';
}