name: PR project validity

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: "Setup release rules"
        run: node scripts/set-release-rules.mjs

      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  check-build:
    name: Check project
    runs-on: ubuntu-latest
    needs: validate-title
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: check-pr.yml

      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: install
          php_version: "8.2"
          version: 1

      - name: Test
        uses: php-actions/composer@v6
        with:
          command: test
          php_version: "8.2"
          version: 1
